[build]
  publish="dist"

[context.production.environment]
  VUE_APP_API="toml production api"
  VUE_APP_SQUAREUP_APPLICATION_ID="sandbox-sq0idb-NpT7hhU92fIF2OeEgtozxA"
  VUE_APP_SQUAREUP_FORM_BUILDER_URL="https://js.squareupsandbox.com/v2/paymentform"

[context.development.environment]
  VUE_APP_API="toml dev api"
  VUE_APP_SQUAREUP_APPLICATION_ID="sandbox-sq0idb-NpT7hhU92fIF2OeEgtozxA"
  VUE_APP_SQUAREUP_FORM_BUILDER_URL="https://js.squareupsandbox.com/v2/paymentform"
  
[context.staging.environment]
  VUE_APP_API="toml staging api"
  VUE_APP_SQUAREUP_APPLICATION_ID="sandbox-sq0idb-NpT7hhU92fIF2OeEgtozxA"
  VUE_APP_SQUAREUP_FORM_BUILDER_URL="https://js.squareupsandbox.com/v2/paymentform"