[build]
  publish="dist"

[context.production.environment]
  VUE_APP_API=process.env.API_PRODUCTION
  VUE_APP_SQUAREUP_APPLICATION_ID=process.env.SQUAREUP_SANDBOX_APPLICATION_ID
  VUE_APP_SQUAREUP_FORM_BUILDER_URL=process.env.SQUARE_SANDBOX_FORM_BUILDER

[context.staging.environment]
  VUE_APP_API=process.env.API_STAGING
  VUE_APP_SQUAREUP_APPLICATION_ID=process.env.SQUAREUP_APPLICATION_ID
  VUE_APP_SQUAREUP_FORM_BUILDER_URL=process.env.SQUARE_FORM_BUILDER

[context.development.environment]
  VUE_APP_API=process.env.API_DEVELOPMENT
  VUE_APP_SQUAREUP_APPLICATION_ID=process.env.SQUAREUP_APPLICATON_ID
  VUE_APP_SQUAREUP_FORM_BUILDER_URL=process.env.SQUARE_FORM_BUILDER